#!/usr/bin/env node
// engine.schema.json (the output of `femlab schema`) → TypeScript for packages/registry.
//   node tools/codegen.mjs [--from <engine.schema.json>] [--check]
// Writes packages/registry/src/generated/engine.ts (types) and fem.d.ts (script API).
// --check regenerates in memory and exits 1 if either committed file differs.
// Node only, no shell, no Rust toolchain: the schema document is committed.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { commandReference } from './command-docs.mjs';

const BANNER = '/* generated by tools/codegen.mjs — do not edit */';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const gen = path.join(root, 'packages', 'registry', 'src', 'generated');

/** Top-level schema key → exported type name (`Error` would shadow the global). */
const TOP = {
  commands: 'Command',
  queries: 'Query',
  queryResult: 'QueryResult',
  ack: 'Ack',
  error: 'EngineError',
  modelFile: 'ModelFile',
};

/** Rewrite every `#/$defs/<old>` to `#/$defs/<new>` per `rename`. */
function retarget(node, rename) {
  if (Array.isArray(node)) return node.map((n) => retarget(n, rename));
  if (!node || typeof node !== 'object') return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === '$ref' && typeof v === 'string' && v.startsWith('#/$defs/')) {
      const name = v.slice('#/$defs/'.length);
      out[k] = `#/$defs/${rename[name] ?? name}`;
    } else out[k] = retarget(v, rename);
  }
  return out;
}

/**
 * `femlab schema` emits six independent JSON Schemas, each with its own `$defs`, and
 * json-schema-to-typescript resolves `#/$defs/..` against the root it is given. Compiling them
 * one by one would declare `Quantity` six times, so fold them into one root with one `$defs`
 * table. Same-named defs that are byte-identical are shared; the few that differ (the model
 * file's SI predicates vs the Command's unit-string predicates) are prefixed with their table's
 * type name, e.g. `ModelFile_FacePredicate`, and their `$ref`s rewritten.
 */
/**
 * `json-schema-to-typescript` treats a `$ref` alongside sibling keywords as "ignore everything
 * but the ref", which is what schemars emits for an internally tagged enum's newtype variant:
 * the tag's `const` sits in `properties`/`required` beside a `$ref` to the wrapped struct
 * (`MesherSpec::Tet(TetSpec)` → `{ properties: { kind: {...} }, $ref: '#/$defs/TetSpec' }`).
 * Both halves are meant to apply — merge the referenced schema's `properties`/`required` into
 * the node and drop the `$ref`, so the generated type carries the wrapped struct's own fields
 * as well as the tag.
 */
function inlineRefSiblings(node, defs) {
  if (Array.isArray(node)) return node.map((n) => inlineRefSiblings(n, defs));
  if (!node || typeof node !== 'object') return node;
  const out = {};
  for (const [k, v] of Object.entries(node)) out[k] = inlineRefSiblings(v, defs);
  if (typeof out.$ref === 'string' && out.$ref.startsWith('#/$defs/') && Object.keys(out).length > 1) {
    const target = defs[out.$ref.slice('#/$defs/'.length)];
    if (target) {
      const { $ref, properties, required, ...siblings } = out;
      return {
        ...target,
        ...siblings,
        properties: { ...(target.properties ?? {}), ...properties },
        required: [...new Set([...(target.required ?? []), ...(required ?? [])])],
      };
    }
  }
  return out;
}

export function mergeSchema(doc) {
  const defs = {};
  const properties = {};
  for (const [key, name] of Object.entries(TOP)) {
    // eslint-disable-next-line no-unused-vars
    const { $schema, title, $defs = {}, ...body } = doc[key];
    const rename = {};
    for (const [k, v] of Object.entries($defs)) {
      if (defs[k] && JSON.stringify(defs[k]) !== JSON.stringify(v)) rename[k] = `${name}_${k}`;
    }
    const fixed = retarget({ ...body, $defs }, rename);
    for (const [k, v] of Object.entries(fixed.$defs)) defs[rename[k] ?? k] = v;
    delete fixed.$defs;
    if (defs[name] && JSON.stringify(defs[name]) !== JSON.stringify(fixed)) {
      throw new Error(`top-level ${name} collides with a different $defs entry of the same name`);
    }
    defs[name] = fixed;
    properties[key] = { $ref: `#/$defs/${name}` };
  }
  const inlinedDefs = Object.fromEntries(Object.entries(defs).map(([k, v]) => [k, inlineRefSiblings(v, defs)]));
  return {
    $schema: doc.commands.$schema,
    title: 'Engine',
    description: `Every wire type of the FEM Lab engine, schema version ${doc.schemaVersion}.`,
    type: 'object',
    properties: inlineRefSiblings(properties, defs),
    required: Object.keys(properties),
    additionalProperties: false,
    $defs: inlinedDefs,
  };
}

const jsdoc = (text, indent) =>
  text ? `${indent}/**\n${text.split('\n').map((l) => `${indent} * ${l}`.trimEnd()).join('\n')}\n${indent} */\n` : '';

/**
 * `new` alone would be a construct signature and a non-identifier would not parse, so those
 * names are quoted. A quoted member is still reached as `fem.model.new(...)`.
 */
const member = (verb) => (verb === 'new' || !/^[A-Za-z_$][\w$]*$/.test(verb) ? JSON.stringify(verb) : verb);

/**
 * One method per Command/Query variant, grouped by namespace:
 * `geometry.addBox` → `fem.geometry.addBox(args): Promise<Ack>`,
 * `query.probe` → `fem.query.probe(args): Promise<ProbeResult>` (`x-returns`).
 * `args` is omitted when the variant has no other properties and optional when none is required.
 */
export function femDts(doc) {
  const groups = new Map();
  const returns = new Set(['Ack', 'Command', 'Query']);
  const add = (variant, tag, union, ret) => {
    const [ns, verb] = variant.properties[tag].const.split('.');
    const props = Object.keys(variant.properties).filter((p) => p !== tag);
    const required = (variant.required ?? []).filter((p) => p !== tag);
    const argType = `Omit<Extract<${union}, { ${tag}: '${ns}.${verb}' }>, '${tag}'>`;
    const args = props.length === 0 ? '' : `args${required.length === 0 ? '?' : ''}: ${argType}`;
    returns.add(ret);
    if (!groups.has(ns)) groups.set(ns, []);
    groups.get(ns).push(`${jsdoc(variant.description, '    ')}    ${member(verb)}(${args}): Promise<${ret}>;`);
  };
  for (const v of doc.commands.oneOf) add(v, 'cmd', 'Command', 'Ack');
  for (const v of doc.queries.oneOf) add(v, 'query', 'Query', v['x-returns']);
  const body = [...groups]
    .map(([ns, methods]) => `  ${ns}: {\n${methods.join('\n')}\n  };`)
    .join('\n');
  return `${BANNER}\nimport type { ${[...returns].sort().join(', ')} } from './engine';\n\n/** The script API: \`fem.<namespace>.<verb>(args)\`. Commands resolve to an Ack, Queries to their response type. */\nexport interface Fem {\n${body}\n}\n`;
}

export async function generate(doc) {
  const engine = await compile(mergeSchema(doc), 'Engine', {
    additionalProperties: false,
    bannerComment: BANNER,
    strictIndexSignatures: true,
  });
  return { 'engine.ts': engine, 'fem.d.ts': femDts(doc) };
}

async function main(argv) {
  const check = argv.includes('--check');
  const i = argv.indexOf('--from');
  const from = i >= 0 ? path.resolve(argv[i + 1]) : path.join(gen, 'engine.schema.json');
  const doc = JSON.parse(readFileSync(from, 'utf8'));
  const files = await generate(doc);
  let stale = 0;
  const outputs = Object.entries(files).map(([name, text]) => [path.join(gen, name), text]);
  outputs.push([path.join(root, 'docs', 'COMMANDS.md'), commandReference(doc)]);
  for (const [target, text] of outputs) {
    if (check) {
      let current = '';
      try {
        current = readFileSync(target, 'utf8');
      } catch {
        /* missing counts as stale */
      }
      if (current !== text) {
        console.error(`${path.relative(root, target)} is stale; run \`npm run codegen\``);
        stale++;
      }
    } else {
      writeFileSync(target, text);
      console.log(`wrote ${path.relative(root, target)}`);
    }
  }
  process.exit(stale ? 1 : 0);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
