// Human-readable engine registry reference, derived only from the committed schema.
const cell = (value) => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('|', '&#124;').replaceAll('`', '&#96;').replace(/\s*\n\s*/g, ' ');
const anchor = (group, name) => `${group}-${name.replace(/[^a-zA-Z0-9_-]/g, '-')}`;

export function commandReference(doc) {
  const lines = [
    '# Engine Command and Query reference', '',
    '<!-- Generated by npm run codegen from engine.schema.json. Do not edit by hand. -->', '',
    `[Documentation home](README.md) · [Getting started](GETTING-STARTED.md) · [Source JSON Schema](../packages/registry/src/generated/engine.schema.json)`, '',
    `Schema version: ${doc.schemaVersion}. This reference covers engine Commands and Queries. Browser actions such as camera, panels and file pickers are host capabilities: inspect \`fem.registry.list()\` in the browser for the combined registry.`, '',
    'Commands are dispatched as JSON objects containing `cmd`; Queries contain `query`. Other fields are arguments. Required arguments must be supplied; optional arguments use the schema default when one is declared. Units belong in quantity strings such as `210 GPa` and `100 mm`.', '',
    '```js',
    "await fem.dispatch({ cmd: 'model.new', name: 'demo' });",
    "await fem.query.model();",
    '```', '',
    'The field schemas below preserve enums, bounds, alternatives and defaults. `$ref` names resolve in the definitions belonging to the same section. Query responses are named by `x-returns`; their full wire schemas are in the source document’s `queryResult`. Commands return an Ack; failures return structured errors (`code`, `cause`, `where`, `suggestion`).', '',
  ];
  for (const [group, discriminator, title] of [['commands', 'cmd', 'Commands'], ['queries', 'query', 'Queries']]) {
    const schema = doc[group];
    const entries = schema.oneOf.map((entry) => {
      const name = entry.properties?.[discriminator]?.const;
      if (typeof name !== 'string') throw new Error(`Missing ${discriminator} discriminator in ${group}`);
      return { entry, name };
    }).sort((a, b) => a.name.localeCompare(b.name, 'en'));
    lines.push(`## ${title}`, '', ...entries.map(({ name }) => `- [${name}](#${anchor(group, name)})`), '');
    for (const { entry, name } of entries) {
      lines.push(`<a id="${anchor(group, name)}"></a>`, '', `### ${name}`, '', (entry.description ?? '').trim(), '');
      if (entry['x-returns']) lines.push(`Returns: \`${entry['x-returns']}\`.`, '');
      lines.push('| Argument | Required | Schema | Description |', '| --- | --- | --- | --- |');
      for (const [field, definition] of Object.entries(entry.properties)) {
        const { description = '', ...shape } = definition;
        lines.push(`| ${cell(field)} | ${entry.required?.includes(field) ? 'yes' : 'no'} | <code>${cell(JSON.stringify(shape))}</code> | ${cell(description)} |`);
      }
      lines.push('');
    }
    lines.push(`### ${title} definitions`, '', 'Expand a definition to inspect its complete schema. Definition names are local to this section.', '');
    for (const [name, definition] of Object.entries(schema.$defs ?? {}).sort(([a], [b]) => a.localeCompare(b, 'en'))) {
      lines.push('<details>', `<summary>${cell(name)}</summary>`, '', '```json', JSON.stringify(definition, null, 2), '```', '', '</details>', '');
    }
  }
  return lines.join('\n');
}
